"""Sweep statements/ and regenerate CARRIERS.md.

Status is measured, not declared: a carrier counts as Verified only when its
extracted rows sum to the totals the statement itself prints.

    python scripts/carriers_report.py
"""

from __future__ import annotations

import pathlib
import sys
import warnings
from collections import defaultdict

warnings.filterwarnings("ignore")
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from app.extract import carrier_from_filename, parse_pdf  # noqa: E402
from app.tabular import parse_delimited  # noqa: E402

STATEMENTS = pathlib.Path("statements")
OUT = pathlib.Path("CARRIERS.md")

LABEL = {
    "verified": ("Verified", "Parsed and reconciles against the statement's own totals."),
    "unverified": ("Unverified", "Parsed, but no totals row to cross-check (or it disagrees). Review before use."),
    "no-table": ("No table", "Text layer present but no table found. Needs a template or the LLM fallback."),
    "no-rows": ("No rows", "Table located but no data rows matched."),
    "needs-ocr": ("Needs OCR", "Image-only scan, no text layer. Blocked until OCR is added."),
    "crash": ("Crash", "Parser raised an exception."),
}
ORDER = list(LABEL)
RANK = {b: i for i, b in enumerate(ORDER)}


def bucket(r: dict) -> str:
    w = r["warn"]
    if w.startswith("CRASH"):
        return "crash"
    if "image-only scan" in w:
        return "needs-ocr"
    if "no table could be located" in w:
        return "no-table"
    if r["checks"] and r["passed"] == r["checks"]:
        return "verified"
    if r["rows"]:
        return "unverified"
    return "no-rows"


def scan() -> list[dict]:
    results = []
    for p in sorted(STATEMENTS.glob("*")):
        suffix = p.suffix.lower()
        if suffix == ".pdf":
            reader = parse_pdf
        elif suffix in (".csv", ".tsv"):
            reader = parse_delimited
        else:
            continue
        try:
            s = reader(str(p), p.name)
            results.append({
                "carrier": carrier_from_filename(p.name),
                "template": s.template,
                "rows": len(s.rows),
                "checks": len(s.checks),
                "passed": sum(1 for c in s.checks if c.ok),
                "failsafe": s.payout.status if s.payout else "no_reference",
                "exported": s.payout.exported_total if s.payout else None,
                "declared": (s.payout.statement_total or s.payout.filename_total)
                if s.payout else None,
                "warn": s.warnings[0] if s.warnings else "",
            })
        except Exception as exc:
            results.append({
                "carrier": carrier_from_filename(p.name), "template": "",
                "rows": 0, "checks": 0, "passed": 0,
                "failsafe": "no_reference", "exported": None, "declared": None,
                "warn": f"CRASH: {type(exc).__name__}: {exc}",
            })
        print(f"  scanned {p.name}", file=sys.stderr)
    return results


def render(results: list[dict]) -> str:
    by_carrier: dict[str, list[dict]] = defaultdict(list)
    for r in results:
        by_carrier[r["carrier"]].append(r)

    rows = []
    for carrier, files in sorted(by_carrier.items(), key=lambda kv: kv[0].lower()):
        best = min(files, key=lambda r: RANK[bucket(r)])
        rows.append((carrier, bucket(best), best, files))

    counts = {b: sum(1 for _, x, _, _ in rows if x == b) for b in ORDER}

    L = [
        "# Carrier support",
        "",
        "Generated by `python scripts/carriers_report.py` from a sweep of every PDF in",
        "`statements/`. Status is **measured**, not declared: a carrier only counts as",
        "Verified when the extracted rows sum to the totals the statement itself prints.",
        "",
        f"**{len(rows)} carriers / {len(results)} files.** "
        + " | ".join(f"{LABEL[b][0]}: {counts[b]}" for b in ORDER if counts[b]),
        "",
        "## Status meanings",
        "",
        "| Status | Meaning |",
        "|---|---|",
    ]
    L += [f"| {LABEL[b][0]} | {LABEL[b][1]} |" for b in ORDER if counts[b]]
    fs_counts = {}
    for _, _, best, _ in rows:
        fs_counts[best["failsafe"]] = fs_counts.get(best["failsafe"], 0) + 1
    FS = {"match": "PASS", "mismatch": "**FAIL**", "no_amounts": "n/a", "no_reference": "n/a"}

    L += [
        "",
        "## Failsafe",
        "",
        "Independently of the in-table checks, the amounts headed for Excel are summed",
        "and reconciled against the total the statement *declares* - the amount in the",
        "filename and any labelled total in the statement text. A FAIL blocks export,",
        "in the UI and at the API. See `_payout_check` in `app/extract.py`.",
        "",
        f"PASS: {fs_counts.get('match', 0)} | "
        f"FAIL: {fs_counts.get('mismatch', 0)} | "
        f"Could not run: {fs_counts.get('no_amounts', 0) + fs_counts.get('no_reference', 0)}",
        "",
        "## Carriers",
        "",
        "| Carrier | Status | Failsafe | Exported | Declared | Rows | Checks | Parsed by |",
        "|---|---|---|---:|---:|---:|---:|---|",
    ]

    for carrier, b, best, files in rows:
        tmpl = best["template"]
        if "auto-detected" in tmpl:
            how = "auto-detected"
        elif "delimited export" in tmpl:
            how = "CSV/TSV cleaner"
        elif tmpl:
            how = "hand-written template"
        else:
            how = "-"
        chk = f"{best['passed']}/{best['checks']}" if best["checks"] else "-"
        nf = f" ({len(files)} files)" if len(files) > 1 else ""
        exp = f"{best['exported']:,.2f}" if isinstance(best["exported"], float) else "-"
        dec = f"{best['declared']:,.2f}" if isinstance(best["declared"], float) else "-"
        L.append(
            f"| {carrier}{nf} | {LABEL[b][0]} | {FS.get(best['failsafe'], 'n/a')} | "
            f"{exp} | {dec} | {best['rows'] or '-'} | {chk} | {how} |"
        )

    L += [
        "",
        "## Adding a carrier",
        "",
        "Most carriers need no code. The generic auto-detector in `app/extract.py` tries",
        "every plausible header band and keeps whichever table reconciles best against the",
        "statement's own totals, so the arithmetic check doubles as the layout chooser.",
        "",
        "Add a hand-written `Template` to `TEMPLATES` only when auto-detection is wrong or",
        "cannot be verified. A template declares:",
        "",
        "- `header_tokens` - lowercased words that must all appear in the header band",
        "- `row_first_cell` - regex the first cell of a data row must match",
        "- `canonical` - maps this carrier's columns onto the shared export schema",
        "- `rate_check` - `(base, rate, result)` for a `base x rate == result` check",
        "",
        "Header tokens are **not unique across carriers**: Amwins' header contains every",
        "token in the Chris Leef template. Keep token sets distinctive. As a safety net, a",
        "template that matches but yields no rows falls through to auto-detection.",
        "",
        "## Known gaps",
        "",
        "- **Needs OCR** carriers are image-only scans with no text layer. They need an OCR",
        "  tier (Tesseract, or AWS Textract for messy tables); the parser reads text layers only.",
        "- **Unverified** rows parsed but could not be reconciled, usually because the",
        "  statement prints no totals row. Treat the figures as a starting point, not truth.",
        "- Auto-detected carriers get their cross-carrier column mapping *inferred* from",
        "  column names (`infer_canonical` in `app/excel.py`). Spot-check the `All Rows`",
        "  sheet before relying on it.",
        "",
    ]
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    OUT.write_text(render(scan()), encoding="utf-8")
    print(f"wrote {OUT}")
